name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: test1
          cx_tenant: single-tenant-perf
          base_uri: https://cxst.perf.cxast.net/ 
          cx_client_id: Jenkins
          cx_client_secret: WKTu5aGgJhUl3YB2bjfi1uIcVLyfsn1n
